name: tensorflow
channels:
  - conda
  - conda-forge
dependencies:
  - python = 3.7
  - pip
  - python-graphviz
  - pip:
    - scikit-learn==0.23.0
    - pandas==0.25.1
    - seaborn==0.11.1
    - imbalanced-learn==0.7.0
    - numpy==1.19.5
    - matplotlib==3.1.1
    - kmodes==0.11.0
    - six==1.15.0
    - pydotplus==2.0.2
    - statsmodels==0.12.1
    - tensorflow==2.6.0
    - tensorflow-hub==0.8.0
    - scipy==1.4.1
    - keras-tuner==1.0.1
    - pillow==7.2.0
    - jupyter==1.0.0
    - h5py==3.1.0
    - import-ipynb==0.1.3
    - easyai==1.0.0.4


